//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public int ID { get; set; }
        public int IdTipoDocumentoId { get; set; }
        public int IdTipoParentesco { get; set; }
        public int IdCuentaAhorro { get; set; }
        public string DocumentoId { get; set; }
        public string Nombre { get; set; }
        public int Porcentaje { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaDesactivo { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
    
        public virtual CuentaAhorro CuentaAhorro { get; set; }
        public virtual TipoDocumentoId TipoDocumentoId { get; set; }
        public virtual TipoParentesco TipoParentesco { get; set; }
    }
}
