//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.CuentaAhorro = new HashSet<CuentaAhorro>();
        }
    
        public int ID { get; set; }
        public int IdTipoDocumentoId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string DocumentoId { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string email { get; set; }
    
        public virtual TipoDocumentoId TipoDocumentoId { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaAhorro> CuentaAhorro { get; set; }
    }
}
