//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BancoEntities1 : DbContext
    {
        public BancoEntities1()
            : base("name=BancoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficiario> Beneficiario { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CuentaAhorro> CuentaAhorro { get; set; }
        public virtual DbSet<CuentaObjeto> CuentaObjeto { get; set; }
        public virtual DbSet<EstadoCuenta> EstadoCuenta { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<TipoCuentaAhorro> TipoCuentaAhorro { get; set; }
        public virtual DbSet<TipoDocumentoId> TipoDocumentoId { get; set; }
        public virtual DbSet<TipoMovimiento> TipoMovimiento { get; set; }
        public virtual DbSet<TipoParentesco> TipoParentesco { get; set; }
    
        public virtual int banco_dbo_actualizarDocumentoIdentificacionBeneficiario(string nuevoNumeroDocumentoId, Nullable<int> id)
        {
            var nuevoNumeroDocumentoIdParameter = nuevoNumeroDocumentoId != null ?
                new ObjectParameter("NuevoNumeroDocumentoId", nuevoNumeroDocumentoId) :
                new ObjectParameter("NuevoNumeroDocumentoId", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_actualizarDocumentoIdentificacionBeneficiario", nuevoNumeroDocumentoIdParameter, idParameter);
        }
    
        public virtual int banco_dbo_actualizarEmailBeneficiario(string nuevoEmail, Nullable<int> id)
        {
            var nuevoEmailParameter = nuevoEmail != null ?
                new ObjectParameter("NuevoEmail", nuevoEmail) :
                new ObjectParameter("NuevoEmail", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_actualizarEmailBeneficiario", nuevoEmailParameter, idParameter);
        }
    
        public virtual int banco_dbo_actualizarFechaNacimientoBeneficiario(Nullable<System.DateTime> nuevaFechaNacimiento, Nullable<int> id)
        {
            var nuevaFechaNacimientoParameter = nuevaFechaNacimiento.HasValue ?
                new ObjectParameter("NuevaFechaNacimiento", nuevaFechaNacimiento) :
                new ObjectParameter("NuevaFechaNacimiento", typeof(System.DateTime));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_actualizarFechaNacimientoBeneficiario", nuevaFechaNacimientoParameter, idParameter);
        }
    
        public virtual int banco_dbo_actualizarNombreBeneficiario(string nuevoNombre, Nullable<int> id)
        {
            var nuevoNombreParameter = nuevoNombre != null ?
                new ObjectParameter("NuevoNombre", nuevoNombre) :
                new ObjectParameter("NuevoNombre", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_actualizarNombreBeneficiario", nuevoNombreParameter, idParameter);
        }
    
        public virtual int banco_dbo_actualizarParentescoBeneficiario(string nuevoParentesco, Nullable<int> id)
        {
            var nuevoParentescoParameter = nuevoParentesco != null ?
                new ObjectParameter("NuevoParentesco", nuevoParentesco) :
                new ObjectParameter("NuevoParentesco", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_actualizarParentescoBeneficiario", nuevoParentescoParameter, idParameter);
        }
    
        public virtual int banco_dbo_actualizarPorcentajeBeneficiario(Nullable<int> nuevoPorcentaje, Nullable<int> id, Nullable<int> idCuentaAhorro)
        {
            var nuevoPorcentajeParameter = nuevoPorcentaje.HasValue ?
                new ObjectParameter("NuevoPorcentaje", nuevoPorcentaje) :
                new ObjectParameter("NuevoPorcentaje", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var idCuentaAhorroParameter = idCuentaAhorro.HasValue ?
                new ObjectParameter("IdCuentaAhorro", idCuentaAhorro) :
                new ObjectParameter("IdCuentaAhorro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_actualizarPorcentajeBeneficiario", nuevoPorcentajeParameter, idParameter, idCuentaAhorroParameter);
        }
    
        public virtual int banco_dbo_consultarBeneficiariosCuenta(string numeroCuenta)
        {
            var numeroCuentaParameter = numeroCuenta != null ?
                new ObjectParameter("numeroCuenta", numeroCuenta) :
                new ObjectParameter("numeroCuenta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_consultarBeneficiariosCuenta", numeroCuentaParameter);
        }
    
        public virtual ObjectResult<banco_dbo_consultarEstadoCuenta_Result> banco_dbo_consultarEstadoCuenta(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<banco_dbo_consultarEstadoCuenta_Result>("banco_dbo_consultarEstadoCuenta", idParameter);
        }
    
        public virtual ObjectResult<banco_dbo_ejecutarInserciones_Result> banco_dbo_ejecutarInserciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<banco_dbo_ejecutarInserciones_Result>("banco_dbo_ejecutarInserciones");
        }
    
        public virtual int banco_dbo_eliminarBeneficiario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_eliminarBeneficiario", idParameter);
        }
    
        public virtual int banco_dbo_insertarBeneficiarioXml()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_insertarBeneficiarioXml");
        }
    
        public virtual int banco_dbo_insertarClienteXml()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_insertarClienteXml");
        }
    
        public virtual int banco_dbo_insertarCuentaAhorroXml()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_insertarCuentaAhorroXml");
        }
    
        public virtual int banco_dbo_insertarCuentaObjetoXml()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_insertarCuentaObjetoXml");
        }
    
        public virtual int banco_dbo_insertarEstadoCuentaXml()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_insertarEstadoCuentaXml");
        }
    
        public virtual int banco_dbo_insertarMonedaXml()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_insertarMonedaXml");
        }
    
        public virtual int banco_dbo_insertarTipoDocumentoIdXml()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_insertarTipoDocumentoIdXml");
        }
    
        public virtual int banco_dbo_insertarTipoParentescoXml()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_insertarTipoParentescoXml");
        }
    
        public virtual ObjectResult<banco_dbo_limpiarTablas_Result> banco_dbo_limpiarTablas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<banco_dbo_limpiarTablas_Result>("banco_dbo_limpiarTablas");
        }
    
        public virtual int banco_dbo_Login(string usuario, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("banco_dbo_Login", usuarioParameter, contrasenaParameter);
        }
    
        public virtual int spFill()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spFill");
        }
    
        public virtual int spLinkTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spLinkTables");
        }
    
        public virtual int spResetDB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spResetDB");
        }
    }
}
