//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCuentaAhorro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoCuentaAhorro()
        {
            this.CuentaAhorro = new HashSet<CuentaAhorro>();
        }
    
        public int ID { get; set; }
        public int IdMoneda { get; set; }
        public string Nombre { get; set; }
        public double TasaInteresesAnual { get; set; }
        public int Retiros { get; set; }
        public decimal SaldoMinimo { get; set; }
        public decimal MultaRetirosCajero { get; set; }
        public decimal MultaSaldoMinimo { get; set; }
        public decimal MontoMensual { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaAhorro> CuentaAhorro { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
